services:
  - type: web
    name: subdomain-enum-api
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: SUBDOMAINX_API_KEY
        generateValue: true
      - key: PORT
        value: 8000
    plan: free
